# Generated by Django 5.0.2 on 2025-05-09 08:29

import a_rchat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rchat', '0002_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=a_rchat.models.generate_group_name, max_length=100, unique=True),
        ),
    ]
