# Generated by Django 5.2 on 2025-05-06 06:18

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rchat', '0008_alter_chatgroup_admin_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='groupchat_name',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=100, unique=True),
        ),
    ]
